# =============================================================================
# Lead model conceptualization and development (theory, methodology, and
# implementation), software architecture & model coding (all components),
# data acquisition & processing, team supervision: Michael Miess
# Initial software architecture development, first coding, technical consulting:
# Joel Foramitti
# Lead of energy modeling: Ansir Ilyas
# Lead of water modeling: Dan Wang
# Model consulting & support: Asjad Naqvi
# Project conceptualization, funding & supervision: Yoshihide Wada
# =============================================================================

import numpy as np

def calculate_green_exports_and_substitution(v, p, pc, t):
    """
    Calculates:
    1. NON-OIL Exports generated by Net Zero Industrialization.
    2. Import Substitution (reduction of imports) due to local green manufacturing.
    
    This modifies v.EX_non_oil_ (adds exports) AND v.IM_ (subtracts imports).
    """
    
    # --- 1. PARAMETERS & SETUP ---
    h2_price_sar_gj = getattr(p, 'hydrogen_export_price_sar_gj', 90.0) 
    carbon_price_sar_ton = getattr(p, 'global_carbon_price_sar', 37.0)
    
    # Local content ramp-up (0% -> 50%)
    if t < 5:
        local_content_pct = 0.0
    elif t < 10:
        local_content_pct = 0.0 + (0.06 * (t - 5)) 
    else:
        local_content_pct = 0.50
        
    export_multiplier = 0.10 

    # Robust Sector Lookup
    def get_idx(name, default_idx):
        if hasattr(pc, 'sectors') and name in pc.sectors:
            return pc.sectors.index(name)
        return default_idx

    chem_idx = get_idx('Manufacture of chemicals and chemical products', 3)
    elec_idx = get_idx('Manufacture of electrical equipment', 4)
    mach_idx = get_idx('Manufacture of machinery and equipment n.e.c.', 5)
    agri_idx = get_idx('Agriculture, Forestry & Fishing', 0)

    # --- 2. COMPONENT A: GREEN HYDROGEN (Export Only) ---
    h2_vol_gj = v.hydrogen_export[t] 
    h2_export_val = (h2_vol_gj * h2_price_sar_gj) / 1000.0
    v.EX_non_oil_[t][chem_idx] += h2_export_val

    # --- 3. COMPONENT B: GREEN MANUFACTURING (Export + Import Substitution) ---
    
    # --- B1. Solar PV & Batteries (Electrical Equipment) ---
    # Total Investment demand for Solar/Batteries
    inv_solar_battery = v.I_solar[t] * 1.2 
    
    # Export Value
    solar_export_val = inv_solar_battery * local_content_pct * export_multiplier
    v.EX_non_oil_[t][elec_idx] += solar_export_val
    
    # Import Substitution Value
    # Logic: Without local content, this investment would be imported.
    # The amount we now make locally is the amount we DO NOT import.
    solar_import_substitution = inv_solar_battery * local_content_pct
    
    # Apply Substitution (Reduce Imports, floor at 0)
    v.IM_[t][elec_idx] = np.maximum(0, v.IM_[t][elec_idx] - solar_import_substitution)

    # --- B2. Wind & Electrification (Machinery) ---
    inv_wind_elec = v.I_wind[t] + v.I_electrification_total[t]
    if hasattr(v, 'I_netzero_ccu_'):
        inv_wind_elec += np.sum(v.I_netzero_ccu_[t])

    # Export Value
    wind_mach_export_val = inv_wind_elec * local_content_pct * export_multiplier
    v.EX_non_oil_[t][mach_idx] += wind_mach_export_val
    
    # Import Substitution Value
    wind_import_substitution = inv_wind_elec * local_content_pct
    
    # Apply Substitution
    v.IM_[t][mach_idx] = np.maximum(0, v.IM_[t][mach_idx] - wind_import_substitution)

    # --- 4. COMPONENT C: CARBON CREDITS (Export Only) ---
    credit_export_val = 0.0
    if getattr(p, 'enable_carbon_market', False):
        total_removal_mt = v.flow_remove_nature[t]
        export_share = 0.20 
        export_vol_tonnes = (total_removal_mt * 1_000_000) * export_share
        credit_export_val = (export_vol_tonnes * carbon_price_sar_ton) / 1000.0
        v.EX_non_oil_[t][agri_idx] += credit_export_val

    # --- 5. COMPONENT D: BATTERY STORAGE (Export + Import Sub) ---
    storage_export_val = 0.0
    
    # Calculate total storage investment
    domestic_storage_market = v.I_storage[t]
    
    # If we have local share data, use it for substitution
    if hasattr(v, 'storage_local_share'):
        # Calculate how much is made locally
        local_storage_val = domestic_storage_market * v.storage_local_share[t]
        
        # This local production replaces imports in the Machinery/Electrical sector
        # (Assuming storage falls under Machinery or Electrical - adjusting to Electrical here for batteries)
        v.IM_[t][elec_idx] = np.maximum(0, v.IM_[t][elec_idx] - local_storage_val)

        if v.storage_local_share[t] >= 0.99:
            storage_export_val = domestic_storage_market * 0.50
            v.EX_non_oil_[t][mach_idx] += storage_export_val

    # --- 6. AGGREGATE ---
    v.EX_non_oil_total[t] = np.sum(v.EX_non_oil_[t])
    
    if hasattr(v, 'green_export_total'):
        v.green_export_total[t] = h2_export_val + solar_export_val + \
                                  wind_mach_export_val + credit_export_val + \
                                  storage_export_val 
                                  
    return v.EX_non_oil_[t]